INSERT INTO country (iso_code, country_name, country_capital, country_independence_date) VALUES ('DO','República Dominicana','Santo Domingo','27/02/1844');
INSERT INTO country (iso_code, country_name, country_capital, country_independence_date) VALUES ('AR','Argentina','Buenos Aires','09/07/1816');
INSERT INTO country (iso_code, country_name, country_capital, country_independence_date) VALUES ('BR','Brasil','Brasilia','07/09/1822');
INSERT INTO country (iso_code, country_name, country_capital, country_independence_date) VALUES ('CL','Chile','Santiago','18/09/1810');
INSERT INTO country (iso_code, country_name, country_capital, country_independence_date) VALUES ('CO','Colombia','Bogotá','20/07/1810');
INSERT INTO country (iso_code, country_name, country_capital, country_independence_date) VALUES ('EC','Ecuador','Quito','10/08/1809');
INSERT INTO country (iso_code, country_name, country_capital, country_independence_date) VALUES ('PE','Perú','Lima','28/07/1821');
INSERT INTO country (iso_code, country_name, country_capital, country_independence_date) VALUES ('VE','Venezuela','Caracas','05/07/1811');
INSERT INTO country (iso_code, country_name, country_capital, country_independence_date) VALUES ('UY','Uruguay','Montevideo','25/08/1825');
INSERT INTO country (iso_code, country_name, country_capital, country_independence_date) VALUES ('PY','Paraguay','Asunción','14/05/1811');
INSERT INTO country (iso_code, country_name, country_capital, country_independence_date) VALUES ('BO','Bolivia','Sucre','06/08/1825');
INSERT INTO country (iso_code, country_name, country_capital, country_independence_date) VALUES ('MX','México','Ciudad de México','16/09/1810');
INSERT INTO country (iso_code, country_name, country_capital, country_independence_date) VALUES ('US','Estados Unidos','Washington D.C.','04/07/1776');
INSERT INTO country (iso_code, country_name, country_capital, country_independence_date) VALUES ('CA','Canadá','Ottawa','01/07/1867');
INSERT INTO country (iso_code, country_name, country_capital, country_independence_date) VALUES ('GT','Guatemala','Ciudad de Guatemala','15/09/1821');
INSERT INTO country (iso_code, country_name, country_capital, country_independence_date) VALUES ('CR','Costa Rica','San José','15/09/1821');
INSERT INTO country (iso_code, country_name, country_capital, country_independence_date) VALUES ('SV','El Salvador','San Salvador','15/09/1821');
INSERT INTO country (iso_code, country_name, country_capital, country_independence_date) VALUES ('HN','Honduras','Tegucigalpa','15/09/1821');
INSERT INTO country (iso_code, country_name, country_capital, country_independence_date) VALUES ('NI','Nicaragua','Managua','15/09/1821');
INSERT INTO country (iso_code, country_name, country_capital, country_independence_date) VALUES ('PA','Panamá','Ciudad de Panamá','03/11/1903');
INSERT INTO country (iso_code, country_name, country_capital, country_independence_date) VALUES ('CU','Cuba','La Habana','20/05/1902');
INSERT INTO country (iso_code, country_name, country_capital, country_independence_date) VALUES ('HT','Haití','Puerto Príncipe','01/01/1804');
INSERT INTO country (iso_code, country_name, country_capital, country_independence_date) VALUES ('FR','Francia','París','14/07/1789');
INSERT INTO country (iso_code, country_name, country_capital, country_independence_date) VALUES ('DE','Alemania','Berlín','03/10/1990');
INSERT INTO country (iso_code, country_name, country_capital, country_independence_date) VALUES ('IT','Italia','Roma','17/03/1861');
INSERT INTO country (iso_code, country_name, country_capital, country_independence_date) VALUES ('NL','Países Bajos','Ámsterdam','26/07/1581');
INSERT INTO country (iso_code, country_name, country_capital, country_independence_date) VALUES ('BE','Bélgica','Bruselas','04/10/1830');
INSERT INTO country (iso_code, country_name, country_capital, country_independence_date) VALUES ('PT','Portugal','Lisboa','05/10/1143');
INSERT INTO country (iso_code, country_name, country_capital, country_independence_date) VALUES ('RU','Rusia','Moscú','12/06/1990');
INSERT INTO country (iso_code, country_name, country_capital, country_independence_date) VALUES ('CN','China','Pekín','01/10/1949');
INSERT INTO country (iso_code, country_name, country_capital, country_independence_date) VALUES ('IN','India','Nueva Delhi','15/08/1947');
INSERT INTO country (iso_code, country_name, country_capital, country_independence_date) VALUES ('KR','Corea del Sur','Seúl','15/08/1945');
INSERT INTO country (iso_code, country_name, country_capital, country_independence_date) VALUES ('ID','Indonesia','Yakarta','17/08/1945');
INSERT INTO country (iso_code, country_name, country_capital, country_independence_date) VALUES ('PH','Filipinas','Manila','12/06/1898');
INSERT INTO country (iso_code, country_name, country_capital, country_independence_date) VALUES ('VN','Vietnam','Hanoi','02/09/1945');
INSERT INTO country (iso_code, country_name, country_capital, country_independence_date) VALUES ('EG','Egipto','El Cairo','28/02/1922');
INSERT INTO country (iso_code, country_name, country_capital, country_independence_date) VALUES ('ZA','Sudáfrica','Pretoria','31/05/1910');
INSERT INTO country (iso_code, country_name, country_capital, country_independence_date) VALUES ('NG','Nigeria','Abuya','01/10/1960');
INSERT INTO country (iso_code, country_name, country_capital, country_independence_date) VALUES ('KE','Kenia','Nairobi','12/12/1963');
